video chat/koru/urls.py
from django.urls import path
from . import views

app_name= 'koru'
urlpatterns = [
    path("", views.index, name="index"),
    path("host/", views.host, name="host"),
    path("hostcall/", views.hostcall, name="hostcall"),
    path("users/", views.users, name="users"),
    #path('<str:room_name>/', views.call, name='call'),
]

video chat/videochat/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("koru.urls"))
]

video chat/koru/models.py
from django.db import models

# Create your models here.
class currentchat(models.Model):
    hostname = models.CharField(max_length = 30)
    meetingname = models.CharField(max_length = 30)
    
    def __str__(self):
        return f"Host: {self.hostname} and Meeting ID: {self.meetingname}"

video chat/koru/views.py
from django.shortcuts import render

from .models import currentchat




# Create your views here.

def index(request):
    return render(request,"koru/index.html")

def host(request):
    return render(request, "koru/host.html")


def hostcall(request):
    if request.method == "POST":
        if request.POST.get('name') and request.POST.get('uid'):
            post = currentchat()
            post.hostname = request.POST.get('name')
            post.meetingname = request.POST.get('uid')
            post.save()
            uuid = request.POST.get('uid')
            #return render(request, "koru/Chatroom with uid ie meeting id in database")
    return render(request,"koru/call.html", {"room_name": uuid})

def users(request):
    if request.method == "POST":
        if request.POST.get('name') and request.POST.get('uid'):
            name = request.POST.get('name')    # user's name
            uid = request.POST.get('uid')
            chats = currentchat.objects.values_list("meetingname",flat=True)
            if uid in chats:
                return render(request,"koru/call.html", {"room_name": uid})     #edit
            else:
                return render(request,"koru/nochat.html",{'uid' : uid})
    return render(request,"koru/users.html")


# def call(request, room_name):
#     return render(request, 'koru/call.html', {
#         'room_name': room_name
#     })

video chat/koru/templates/koru/call.html
<!-- chat/templates/chat/room.html -->
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Chat Room</title>
</head>
<body>
<h3>MEETING : {{room_name}}</h3>
<textarea id="chat-log" cols="100" rows="20"></textarea><br>
<input id="chat-message-input" type="text" size="100"><br>
<input id="chat-message-submit" type="button" value="Send">
{{ room_name|json_script:"room-name" }}
<script>
        const roomName = JSON.parse(document.getElementById('room-name').textContent);

        const chatSocket = new WebSocket(
            'ws://'
            + window.location.host
            + '/ws/chat/'
            + roomName
            + '/'
        );

        chatSocket.onmessage = function(e) {
            const data = JSON.parse(e.data);
            document.querySelector('#chat-log').value += (data.message + '\n');
        };

        chatSocket.onclose = function(e) {
            console.error('Chat socket closed unexpectedly');
        };

        document.querySelector('#chat-message-input').focus();
        document.querySelector('#chat-message-input').onkeyup = function(e) {
            if (e.keyCode === 13) {  // enter, return
                document.querySelector('#chat-message-submit').click();
            }
        };

        document.querySelector('#chat-message-submit').onclick = function(e) {
            const messageInputDom = document.querySelector('#chat-message-input');
            const message = messageInputDom.value;
            chatSocket.send(JSON.stringify({
                'message': message
            }));
            messageInputDom.value = '';
        };
    </script>
</body>
</html>

video chat/koru/templates/koru/host.html
{% extends "koru/layout.html" %}

{% block pages %}
    <h2>Host:</h2>
    <form action="{% url 'koru:hostcall' %}" method="post">
        {% csrf_token %}
        <input class="input_box" type="text" placeholder="Name" name="name">
        <br><input class="input_box" type="text" placeholder="Meeting Name" name="uid">
        <br><button class="clickable" style="width:15%" type="submit">Start</button>
    </form>
{% endblock %}

video chat/koru/templates/koru/index.html
{% extends "koru/layout.html" %}

{% block pages %}
        <h2>LET'S GO.</h2><br>
        <a href="{% url 'koru:host' %}"><button class="clickable" style="height:60px;">Host chat</button></a><br>
        <a href="{% url 'koru:users' %}"><button class="clickable" style="height:60px;">Join chat</button></a>
{% endblock %}

video chat/koru/templates/koru/layout.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>koru</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{% static 'koru/styles.css' %}" rel="stylesheet">
    <link rel="shortcut icon" type="image/png" href="{% static 'koru/came.ico' %}"/>
</head>
<body>

<!-- Header -->
<div class="header">
    <h2>Video Chat</h2>
</div>

<!-- Navigation Bar -->
<div class="navbar">
    <a href="{% url 'koru:index' %}">home</a>
</div>

<!-- The flexible grid (content) -->
<div class="row">
    <div class="side">
        <h2>KORU</h2>
        <img src="{% static 'koru/pic1.jpg' %}" alt="sketch" style="height:250px;">
    </div>
    <div class="main">
        {% block pages %}
        {% endblock %}
    </div>
</div>

<!-- Footer -->
<div class="footer">
    <h2>Footer</h2>
</div>

</body>
</html>

video chat/koru/templates/koru/nochat.html
{% extends "koru/layout.html" %}

{% block pages %}
<h1>Error 404!!!</h1><br>
<h2>No Active Chat Found with Meeting Name: {{uid}}</h2><br>
<a href="{% url 'koru:users' %}"><button class="clickable" style="height:60px;">Try different Meeting Name</button></a>
{% endblock %}

video chat/koru/templates/koru/users.html
{% extends "koru/layout.html" %}

{% block pages %}
    <h2>Peer:</h2>
    <form action="{% url 'koru:users' %}" method="post">
        {% csrf_token %}
        <input class="input_box" type="text" placeholder="Name" name="name">
        <input class="input_box" type="text" placeholder="Meeting Name" name="uid">
        <br><button class="clickable" style="width:15%" type="submit">Join</button>
    </form>
{% endblock %}